
sudo: false
language: node_js
node_js:
    - '7'

before_install:
    - openssl aes-256-cbc -K $encrypted_7ac639a057a3_key -iv $encrypted_7ac639a057a3_iv
      -in client-secret.json.enc -out client-secret.json -d
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then 
          rm -rf $HOME/google-cloud-sdk; 
          export CLOUDSDK_CORE_DISABLE_PROMPTS=1; 
          curl https://sdk.cloud.google.com | bash; 
      fi
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud version
    - gcloud config set project stem-tetris
    - gcloud auth activate-service-account --key-file client-secret.json
    - gcloud debug source gen-repo-info-file # Make the info file for Stackdriver

script:
    - yarn run build

deploy:
    provider: gae
    skip_cleanup: true # Don't let Travis remove the Webpack build
    keyfile: client-secret.json
    project: stem-tetris
    on: master

cache:
    directories:
        - "$HOME/google-cloud-sdk/"
        - "$HOME/.yarn-cache/"

