language: node_js
node_js:
    - '7'

script:
    - yarn run build

deploy:
    provider: gae
    skip_cleanup: true # Don't let Travis remove the Webpack build
    keyfile: client-secret.json
    project: stem-tetris
    on: master

cache:
    yarn: true

before_install:
    - openssl aes-256-cbc -K $encrypted_7ac639a057a3_key -iv $encrypted_7ac639a057a3_iv
      -in client-secret.json.enc -out client-secret.json -d
