sudo: false
language: node_js
node_js:
    - '7'

script:
    - yarn run build

before_deploy:
    - gcloud debug source gen-repo-info-file # Make the info file for Stackdriver

deploy:
    provider: gae
    skip_cleanup: true # Don't let Travis remove the Webpack build
    keyfile: client-secret.json
    project: stem-tetris
    on: master

cache:
    yarn: true
    directories:
        - "$HOME/google-cloud-sdk/"


before_install:
    - openssl aes-256-cbc -K $encrypted_7ac639a057a3_key -iv $encrypted_7ac639a057a3_iv
      -in client-secret.json.enc -out client-secret.json -d
